apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ci-cd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: <dockerhub-username>/k8s-ci-cd-demo:latest
          ports:
            - containerPort: 3000
